### ISSUE TITLE
Please document how to adapte the relationship coming from precise/dns ??

### ISSUE THREAD

**Issue by thomnico** [chuckbutler/DNS-Charm#25]
The ressource Json format  needs to be documented to be able to write the other side of the hook ...

When relating to Clearwate all hooks failed, programmable (non multi) scripts runs BUT not entries are put in db.zone file when using bind..

**Comment by chuckbutler** [comment]
Duplicates #21  - Will reference this when making the update.

Sorry about the breakage @thomnico - I built master and didn't have a chance to circle back to the docs with the breaking change.

**Comment by chuckbutler** [comment]
Closing this issue as a duplicate, and will track/triage in #21
